### PR TITLE
Upgrade to kafka 1.0

### PR DESCRIPTION
**Pull request by danielcopaciu**

### CODE REVIEW

**Review by jakekeeys — APPROVED** [review]

**Review by jakekeeys — CHANGES_REQUESTED** [review]
please hold off merging until people fix tags in prod

**Comment by danielcopaciu** [comment]
Can I merge this? I can't see any latest tags for kafka in prod.

**Comment by jakekeeys** [comment]
i merged a pr to fix the cases where they were... need to double check they've been applied... will do first thing tomorrow

**Review by jakekeeys — APPROVED** [review]
all prod tags have been updated

**Review by JamieAP — APPROVED** [review]

**Pull request merged**
